"""TEST

Revision ID: bf091c2637a7
Revises: 
Create Date: 2024-12-20 03:32:57.989530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf091c2637a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_equipment_id', table_name='equipment')
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.drop_index('idx_equipment_types_id', table_name='equipment_types')
    op.create_index(op.f('ix_equipment_types_id'), 'equipment_types', ['id'], unique=False)
    op.drop_index('idx_rentals_id', table_name='rentals')
    op.create_index(op.f('ix_rentals_id'), 'rentals', ['id'], unique=False)
    op.drop_index('idx_stock_levels_id', table_name='stock_levels')
    op.create_index(op.f('ix_stock_levels_id'), 'stock_levels', ['id'], unique=False)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_id', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_id', 'users', ['id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_stock_levels_id'), table_name='stock_levels')
    op.create_index('idx_stock_levels_id', 'stock_levels', ['id'], unique=False)
    op.drop_index(op.f('ix_rentals_id'), table_name='rentals')
    op.create_index('idx_rentals_id', 'rentals', ['id'], unique=False)
    op.drop_index(op.f('ix_equipment_types_id'), table_name='equipment_types')
    op.create_index('idx_equipment_types_id', 'equipment_types', ['id'], unique=False)
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.create_index('idx_equipment_id', 'equipment', ['id'], unique=False)
    # ### end Alembic commands ###
